FROM dunglas/frankenphp:1-php8.4
RUN install-php-extensions \
    bcmath \
    intl \
    opcache \
    pcntl \
    pdo_mysql \
    pdo_pgsql \
    pdo_sqlite \
    redis \
    zip
WORKDIR /app
ENV APP_ENV=production
COPY . /app
COPY .phpsandbox/cloudflare/Caddyfile /etc/caddy/Caddyfile
COPY .phpsandbox/cloudflare/laravel-start.sh /usr/local/bin/okra-laravel-start
COPY .phpsandbox/cloudflare/launcher.sh /usr/local/bin/okra-deployment-launcher
RUN chmod +x /usr/local/bin/okra-deployment-launcher /usr/local/bin/okra-laravel-start
EXPOSE {{.Port}}
ENTRYPOINT ["/usr/local/bin/okra-deployment-launcher"]
CMD {{.Command}}
